language: python

python:
  - "3.7"

services:
  - sqlite

env: 
  - DJANGO=3.0
    
install:
  - pip install -r requirements.txt

before_script:
  - cd cricket

script:
  - python manage.py loaddata members.json
  - python manage.py test