# Generated by Django 3.0.6 on 2020-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
